version: '3.8'
services:
  preprocessor:
    build: ./microservices/data_preprocessor
    ports:
      - "5001:5001"

  trainer:
    build: ./microservices/trainer
    ports:
      - "5002:5002"

  aggregator:
    build: ./microservices/aggregator
    ports:
      - "5003:5003"

  updater:
    build: ./microservices/global_model_updater
    ports:
      - "5004:5004"

  xai:
    build: ./microservices/xai_service
    ports:
      - "5005:5005"